---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llmops-secrets
  namespace: llm-apps
spec:
  encryptedData:
    GOOGLE_SEARCH_API: AgAaJOemzt4v86q3mnoewgOlNNR2RMFTY+Zz4i2EaEj4rA5DeQo8Y7GohgiWAXC9V2vh5MpcE4aTKS01sJWgMEEco2jQf1GAtsWm79iJRlH9zCAJo5Rf4ts+hi3OYzG4i4y/c3jNNh9uqHe9ogzuWuZCfsH0m003ATJxyQvxTszkh9lS9C/OAyA5MXI7Dd/aqgqdjWr0w7kPDkCr2dvB35pMuC6ZdUlEd26IHsfioF6/AHgaFvAfNuUX0bkvtILMOd2017vpXuG8MRXsM4/8vlr3QSoMeH4jL2YSXPLqOre3fzCqFiwEtcnT9tuY/Z9//3iXJdq/rHDqy3hPk1EMIItt2dyZa9LwzqYXXCLawttiSOJ/0RdjnzLC6DuUAMKtCMUcAXm8GBmjfI/Jqrl3YFlW8kFhctMdagPIgD+q4DxI6ep/FO3tp9j84o0pLkgFu/X20vmp8J29MfjCIDyZJz/2sshGp0RE+Q0KDhHQz82pqkxH1L5b3Kj7zAGfP9fTs5H9KDY5zo4wliYr2wf7/ikCRQH3sSto8Q9WSPSk8HHDtQAzW2rdZUOpDSnmOqm5TnjX1c/qaQcbX5cyqMQ91mg7bCwdU5rGeDnpZSTfanWvmww0VGJQi5tlbviulC+989H5X8LOFYFF9qiB7b9chm93MsPQG5RFZ6IAQfnBuwVVtcw5JTa8HzC8oOrtcVyJtKvI4vR/9Gn27gayKA9HYqXmjcKb+GNJVdPu1QDlvdlcZeua6gQIxfk=
    LITELLM_API_KEY: AgDerP60FZPrByv6XhBSWcgPkyFgqdeiTSrovHDuPL0XtxSN3Ki5BXb6lrqDBVBEs2a5/yrstnf/6AY3vTBb3aiTzZD0eUh8vF+MADi+Wdy9Ebm8snnbj4K/oKlnWNC+KCXpmglom/m31G5LwgmvvsSGSNRVJiLuH2oxYu1ToIwpl+nozzjVPQhkSLco+IJrcmSKcODMrIOiDTcDGU+1n7qHsxBdElz+0ZHWGmp7O9DbrgcHiBrpXDvOpwcEDkcVb31FLf4ZMjkjCNYkwLp2sXaoEMl+/sMNFHpDX18fEturt/e6X4LpMSMyunCi92CYFbZ/Lxd+b0Ux8jE7SbE4L3uFPPK6SNfLHrRoX0+BGmQvCZO0xjX9jsjmI9Wc/m5JomaBaU5kCNJ4cWd9gYjNZXokFmHBOTw5GtijkyujvkHT0otx722RAQoxcPnpp/HBOfdqAf5JWp3UgQ3mSfljBSlg2oyXQv9QywqORMrNbEOQcHj+w6rZL0a+DO5ftTzzGnF9uQqrGVSmHdTCFsKswV8zHhAWDVEEiyFkZq18Hr+vxm2zqjoyUEDyfZxfTQ7MZYflQM3VHz0aMJLhjb40lvyYmSr067+zXiIfcyt/AviAIpRKaXjgg6c9CVitrCsXF5M9aeLMvry8yLQo0dY9LPK/YIq1GxS/qoKE0HkmXZSqzYtvqJxmsy2LEvHrrIJ8GcmMxZmBBbNmpuNYKwXXeijm6mPzE8To31XoYMU=
  template:
    metadata:
      name: llmops-secrets
      namespace: llm-apps
    type: Opaque
