apiVersion: v1
kind: ConfigMap
metadata:
  name: llmops-config
  namespace: llm-apps
data:
  MLFLOW_TRACKING_URI: "http://mlflow.monitoring.svc.cluster.local:5000"
  MLFLOW_REGISTRY_URI: "http://mlflow.monitoring.svc.cluster.local:5000"
  MLFLOW_EXPERIMENT_NAME: "autogen_team_experiment"
  MLFLOW_REGISTERED_MODEL_NAME: "autogen_team_model"
  GOOGLE_CSE_ID: "e1af527f0377843d3"
  DEFAULT_KAFKA_SERVER: "my-kafka-cluster.confluent.svc.cluster.local:9092"
  DEFAULT_GROUP_ID: "llmops-regression"
  DEFAULT_AUTO_OFFSET_RESET: "earliest"
  DEFAULT_INPUT_TOPIC: "llm_input_topic"
  DEFAULT_OUTPUT_TOPIC: "llm_output_topic"
  DEFAULT_FASTAPI_HOST: "0.0.0.0"
  DEFAULT_FASTAPI_PORT: "8100"
  MLFLOW_MODEL_ALIAS: "Champion"
