apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-python-package
  namespace: llm-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops-python-package
  template:
    metadata:
      labels:
        app: llmops-python-package
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "until nc -zv mlflow.monitoring.svc.cluster.local 5000 && nc -zv my-kafka-cluster.confluent.svc.cluster.local 9092; do echo 'Waiting for dependencies...'; sleep 2; done",
            ]
      containers:
        - name: llmops-app
          image: lgcorzo/llmops-python-package:latest
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: llmops-config
            - secretRef:
                name: llmops-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: llmops-python-package
  namespace: llm-apps
spec:
  selector:
    app: llmops-python-package
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP
