apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-python-package
  namespace: llm-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops-python-package
  template:
    metadata:
      labels:
        app: llmops-python-package
    spec:
      containers:
        - name: llmops-app
          image: lgcorzo/llmops-python-package:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: llmops-config
            - secretRef:
                name: llmops-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: llmops-python-package
  namespace: llm-apps
spec:
  selector:
    app: llmops-python-package
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP
